// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhEo4S0yynDRRuC0CME_6fDpvHJmkVNgk',
    appId: '1:3911581639:web:9d256ad62659b4a10423e2',
    messagingSenderId: '3911581639',
    projectId: 'chuvasos',
    authDomain: 'chuvasos.firebaseapp.com',
    storageBucket: 'chuvasos.appspot.com',
    measurementId: 'G-6XGKBZ2G9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG2pnxVSX-erkalSFvyVt7T4K_u4bJmlY',
    appId: '1:3911581639:android:56cee9de19a41cab0423e2',
    messagingSenderId: '3911581639',
    projectId: 'chuvasos',
    storageBucket: 'chuvasos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAadOg-jV8EkLHf8gROTKhGQgIHqPyXaMk',
    appId: '1:3911581639:ios:d94daf4610f4a33b0423e2',
    messagingSenderId: '3911581639',
    projectId: 'chuvasos',
    storageBucket: 'chuvasos.appspot.com',
    iosClientId: '3911581639-mdrspjpr101349hlo2a3id1aonpudfao.apps.googleusercontent.com',
    iosBundleId: 'com.example.chuvasosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAadOg-jV8EkLHf8gROTKhGQgIHqPyXaMk',
    appId: '1:3911581639:ios:d94daf4610f4a33b0423e2',
    messagingSenderId: '3911581639',
    projectId: 'chuvasos',
    storageBucket: 'chuvasos.appspot.com',
    iosClientId: '3911581639-mdrspjpr101349hlo2a3id1aonpudfao.apps.googleusercontent.com',
    iosBundleId: 'com.example.chuvasosApp',
  );
}
